server:
  port: 8761 # Puerto estándar de Eureka

eureka:
  instance:
    hostname: localhost
  client:
    # Como este ES el servidor, le decimos que no se registre a sí mismo
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
